name: build

on:
  workflow_call:
    inputs:
      fct_stack:
        type: string
        required: true
      role_to_assume:
        type: string
        required: true

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: config-creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ inputs.role_to_assume }}
          role-session-name: GitHubActions-${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}
          role-duration-seconds: 1200

      - name: cdk-synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: synth
          cdk_args: '--require-approval never --context stack=${{ inputs.fct_stack }} --progress events --debug'
          actions_comment: false
