name: build

on:
  workflow_call:
    inputs:
      fct_stack:
        type: string
        required: true
      role_to_assume:
        type: string
        required: true

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: checkout
        uses: actions/checkout@v7.0.1

      - name: config-creds
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          aws-region: us-east-1
          role-to-assume: ${{ inputs.role_to_assume }}
          role-session-name: GitHubActions-${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}
          role-duration-seconds: 1200

      - name: setup-python
        uses: actions/setup-python@v7.0.0
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements.txt

      - name: setup-node
        uses: actions/setup-node@v7.0.0
        with:
          node-version: '22'

      - name: install-cdk-cli
        run: npm install -g aws-cdk@2.1139.0

      - name: install-deps
        run: pip install -r requirements.txt

      - name: cdk-deploy
        run: cdk deploy --require-approval never --context fct_stack=${{ inputs.fct_stack }} --progress events --debug
