name: main

on:
  pull_request:
    branches: [ '*' ]
  push:
    branches: [ 'master', 'develop' ]

concurrency: ci-${{ github.ref }}

jobs:

  test:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: test
        uses: pre-commit/action@v3.0.0

  build-dev:
    if: ${{ github.ref_name == 'develop' }}
    uses: ./.github/workflows/build.yaml
    with:
      fct_stack: dev
      role_to_assume: arn:aws:iam::449435941126:role/sagebase-github-oidc-nbconvert-deploy

  build-prod:
    if: ${{ github.ref_name == 'master' }}
    uses: ./.github/workflows/build.yaml
    with:
      fct_stack: prod
# Always deploy to dev for now...
      role_to_assume: arn:aws:iam::449435941126:role/sagebase-github-oidc-nbconvert-deploy
